// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msvdqydebpxfgnidfopg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zdmRxeWRlYnB4ZmduaWRmb3BnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMjk1MjYsImV4cCI6MjA2MTcwNTUyNn0.Vg9G3E4ATnKdcXvFUIOEJi1pW9JSTNQEk_EYsbaZWrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);